<a href="https://colab.research.google.com/github/brunofbpaula/DataScience-UM-Coursera/blob/main/Assignments/Scratches/Assignment3MU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import re

## Energy Indicators

In [77]:
energy = pd.ExcelFile('/content/Energy Indicators.xls')
energy = pd.read_excel(energy, 0, skiprows=17, skipfooter=38)
energy

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Petajoules,Gigajoules,%
0,NaN,Afghanistan,Afghanistan,321,10,78.669280
1,NaN,Albania,Albania,102,35,100.000000
2,NaN,Algeria,Algeria,1959,51,0.551010
3,NaN,American Samoa,American Samoa,...,...,0.641026
4,NaN,Andorra,Andorra,9,121,88.695650
...,...,...,...,...,...,...
222,NaN,Viet Nam,Viet Nam,2554,28,45.321520
223,NaN,Wallis and Futuna Islands,Wallis and Futuna Islands,0,26,0.000000
224,NaN,Yemen,Yemen,344,13,0.000000
225,NaN,Zambia,Zambia,400,26,99.714670
226,NaN,Zimbabwe,Zimbabwe,480,32,52.536120

In [78]:
energy = energy[['Unnamed: 1', 'Petajoules', 'Gigajoules', '%']]
energy

                    Unnamed: 1 Petajoules Gigajoules           %
0                  Afghanistan        321         10   78.669280
1                      Albania        102         35  100.000000
2                      Algeria       1959         51    0.551010
3               American Samoa        ...        ...    0.641026
4                      Andorra          9        121   88.695650
..                         ...        ...        ...         ...
222                   Viet Nam       2554         28   45.321520
223  Wallis and Futuna Islands          0         26    0.000000
224                      Yemen        344         13    0.000000
225                     Zambia        400         26   99.714670
226                   Zimbabwe        480         32   52.536120

[227 rows x 4 columns]

In [79]:
energy = energy.rename(columns={'Unnamed: 1': 'Country',
                                'Petajoules': 'Energy Supply',
                                'Gigajoules': 'Energy Supply per Capita',
                                '%': '% Renewable'})
energy.head()

          Country Energy Supply Energy Supply per Capita  % Renewable
0     Afghanistan           321                       10    78.669280
1         Albania           102                       35   100.000000
2         Algeria          1959                       51     0.551010
3  American Samoa           ...                      ...     0.641026
4         Andorra             9                      121    88.695650

In [80]:
energy['Energy Supply'].replace('...', np.nan, inplace=True)
energy['Energy Supply'] = energy['Energy Supply'] * 1000000
energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+08,10,78.669280
1,Albania,1.020000e+08,35,100.000000
2,Algeria,1.959000e+09,51,0.551010
3,American Samoa,NaN,...,0.641026
4,Andorra,9.000000e+06,121,88.695650
...,...,...,...,...
222,Viet Nam,2.554000e+09,28,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26,0.000000
224,Yemen,3.440000e+08,13,0.000000
225,Zambia,4.000000e+08,26,99.714670
226,Zimbabwe,4.800000e+08,32,52.536120

In [81]:
energy['Country'].replace({'Republic of Korea':'South Korea',
                            'United States of America':'United States',
                            'United Kingdom of Great Britain and Northern Ireland':'United Kingdom',
                            'China, Hong Kong Special Administrative Region':'Hong Kong'}, inplace=True)
energy['Country'].replace(r' \(.*\)', '',regex=True, inplace=True)
energy['Country'].replace(r' \d', '',regex=True, inplace=True)

In [82]:
energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+08,10,78.669280
1,Albania,1.020000e+08,35,100.000000
2,Algeria,1.959000e+09,51,0.551010
3,American Samoa,NaN,...,0.641026
4,Andorra,9.000000e+06,121,88.695650
...,...,...,...,...
222,Viet Nam,2.554000e+09,28,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26,0.000000
224,Yemen,3.440000e+08,13,0.000000
225,Zambia,4.000000e+08,26,99.714670
226,Zimbabwe,4.800000e+08,32,52.536120

## GDP

In [83]:
gdp = pd.read_csv('world_bank.csv', skiprows=4)
gdp['Country Name'].replace({"Korea, Rep.": "South Korea",  "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"}, inplace=True)
gdp = gdp[['Country Name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
gdp.rename(columns={'Country Name': 'Country'}, inplace=True)
for c in gdp['Country']:
  print(c)

Aruba
Andorra
Afghanistan
Angola
Albania
Arab World
United Arab Emirates
Argentina
Armenia
American Samoa
Antigua and Barbuda
Australia
Austria
Azerbaijan
Burundi
Belgium
Benin
Burkina Faso
Bangladesh
Bulgaria
Bahrain
Bahamas, The
Bosnia and Herzegovina
Belarus
Belize
Bermuda
Bolivia
Brazil
Barbados
Brunei Darussalam
Bhutan
Botswana
Central African Republic
Canada
Central Europe and the Baltics
Switzerland
Channel Islands
Chile
China
Cote d'Ivoire
Cameroon
Congo, Rep.
Colombia
Comoros
Cabo Verde
Costa Rica
Caribbean small states
Cuba
Curacao
Cayman Islands
Cyprus
Czech Republic
Germany
Djibouti
Dominica
Denmark
Dominican Republic
Algeria
East Asia & Pacific (excluding high income)
Early-demographic dividend
East Asia & Pacific
Europe & Central Asia (excluding high income)
Europe & Central Asia
Ecuador
Egypt, Arab Rep.
Euro area
Eritrea
Spain
Estonia
Ethiopia
European Union
Fragile and conflict affected situations
Finland
Fiji
France
Faroe Islands
Micronesia, Fed. Sts.
Gabon
United Kingdom
Georgia
Ghana
Gibraltar
Guinea
Gambia, The
Guinea-Bissau
Equatorial Guinea
Greece
Grenada
Greenland
Guatemala
Guam
Guyana
High income
Hong Kong
Honduras
Heavily indebted poor countries (HIPC)
Croatia
Haiti
Hungary
IBRD only
IDA & IBRD total
IDA total
IDA blend
Indonesia
IDA only
Isle of Man
India
Not classified
Ireland
Iran
Iraq
Iceland
Israel
Italy
Jamaica
Jordan
Japan
Kazakhstan
Kenya
Kyrgyz Republic
Cambodia
Kiribati
St. Kitts and Nevis
South Korea
Kosovo
Kuwait
Latin America & Caribbean (excluding high income)
Lao PDR
Lebanon
Liberia
Libya
St. Lucia
Latin America & Caribbean
Least developed countries: UN classification
Low income
Liechtenstein
Sri Lanka
Lower middle income
Low & middle income
Lesotho
Late-demographic dividend
Lithuania
Luxembourg
Latvia
Macao SAR, China
St. Martin (French part)
Morocco
Monaco
Moldova
Madagascar
Maldives
Middle East & North Africa
Mexico
Marshall Islands
Middle income
Macedonia, FYR
Mali
Malta
Myanmar
Middle East & North Africa (excluding high income)
Montenegro
Mongolia
Northern Mariana Islands
Mozambique
Mauritania
Mauritius
Malawi
Malaysia
North America
Namibia
New Caledonia
Niger
Nigeria
Nicaragua
Netherlands
Norway
Nepal
Nauru
New Zealand
OECD members
Oman
Other small states
Pakistan
Panama
Peru
Philippines
Palau
Papua New Guinea
Poland
Pre-demographic dividend
Puerto Rico
Korea, Dem. Peopleâ€™s Rep.
Portugal
Paraguay
Pacific island small states
Post-demographic dividend
French Polynesia
Qatar
Romania
Russian Federation
Rwanda
South Asia
Saudi Arabia
Sudan
Senegal
Singapore
Solomon Islands
Sierra Leone
El Salvador
San Marino
Somalia
Serbia
Sub-Saharan Africa (excluding high income)
South Sudan
Sub-Saharan Africa
Small states
Sao Tome and Principe
Suriname
Slovak Republic
Slovenia
Sweden
Swaziland
Sint Maarten (Dutch part)
Seychelles
Syrian Arab Republic
Turks and Caicos Islands
Chad
East Asia & Pacific (IDA & IBRD countries)
Europe & Central Asia (IDA & IBRD countries)
Togo
Thailand
Tajikistan
Turkmenistan
Latin America & the Caribbean (IDA & IBRD countries)
Middle East & North Africa (IDA & IBRD countries)
Timor-Leste
Tonga
South Asia (IDA & IBRD)
Sub-Saharan Africa (IDA & IBRD countries)
Trinidad and Tobago
Tunisia
Turkey
Tuvalu
Tanzania
Uganda
Ukraine
Upper middle income
Uruguay
United States
Uzbekistan
St. Vincent and the Grenadines
Venezuela, RB
British Virgin Islands
Virgin Islands (U.S.)
Vietnam
Vanuatu
West Bank and Gaza
World
Samoa
Yemen, Rep.
South Africa
Congo, Dem. Rep.
Zambia
Zimbabwe

## ScimEn

In [84]:
ScimEn = pd.read_excel('scimagojr-3.xlsx')
ScimEn = ScimEn[:15]
ScimEn

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57
5,6,Canada,17899,17620,215003,40930,12.01,149
6,7,Germany,17027,16831,140566,27426,8.26,126
7,8,India,15005,14841,128763,37209,8.58,115
8,9,France,13153,12973,130632,28601,9.93,114
9,10,South Korea,11983,11923,114675,22595,9.57,104
10,11,Italy,10964,10794,111850,26661,10.20,106
11,12,Spain,9428,9330,123336,23964,13.08,115
12,13,Iran,8896,8819,57470,19125,6.46,72
13,14,Australia,8831,8725,90765,15606,10.28,107
14,15,Brazil,8668,8596,60702,14396,7.00,86

## Inner join

In [85]:
sci_energy = pd.merge(ScimEn, energy, how='inner', left_on='Country', right_on='Country')
sci_energy

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable
0,1,China,127050,126767,597237,411683,4.70,138,1.271910e+11,93,19.754910
1,2,United States,96661,94747,792274,265436,8.20,230,9.083800e+10,286,11.570980
2,3,Japan,30504,30287,223024,61554,7.31,134,1.898400e+10,149,10.232820
3,4,United Kingdom,20944,20357,206091,37874,9.84,139,7.920000e+09,124,10.600470
4,5,Russian Federation,18534,18301,34266,12422,1.85,57,3.070900e+10,214,17.288680
5,6,Canada,17899,17620,215003,40930,12.01,149,1.043100e+10,296,61.945430
6,7,Germany,17027,16831,140566,27426,8.26,126,1.326100e+10,165,17.901530
7,8,India,15005,14841,128763,37209,8.58,115,3.319500e+10,26,14.969080
8,9,France,13153,12973,130632,28601,9.93,114,1.059700e+10,166,17.020280
9,10,South Korea,11983,11923,114675,22595,9.57,104,1.100700e+10,221,2.279353
10,11,Italy,10964,10794,111850,26661,10.20,106,6.530000e+09,109,33.667230
11,12,Spain,9428,9330,123336,23964,13.08,115,4.923000e+09,106,37.968590
12,13,Iran,8896,8819,57470,19125,6.46,72,9.172000e+09,119,5.707721
13,14,Australia,8831,8725,90765,15606,10.28,107,5.386000e+09,231,11.810810
14,15,Brazil,8668,8596,60702,14396,7.00,86,1.214900e+10,59,69.648030

In [86]:
merged = pd.merge(sci_energy, gdp, how='inner', left_on='Country', right_on='Country')
merged = merged.set_index('Country')
merged

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

## Series

In [87]:
top_fifteen = merged
top_fifteen = top_fifteen[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
top_fifteen

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,
China,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [88]:
avg = top_fifteen.apply(np.nanmean, axis=1)
avg

Country
China                 6.348609e+12
United States         1.536434e+13
Japan                 5.542208e+12
United Kingdom        2.487907e+12
Russian Federation    1.565459e+12
Canada                1.660647e+12
Germany               3.493025e+12
India                 1.769297e+12
France                2.681725e+12
South Korea           1.106715e+12
Italy                 2.120175e+12
Spain                 1.418078e+12
Iran                  4.441558e+11
Australia             1.164043e+12
Brazil                2.189794e+12
dtype: float64

In [89]:
avg
avg = avg.sort_values(ascending=False)
avg

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
dtype: float64

Ok, I'll need the actual function because this has become messy.

In [94]:
# Importing libraries
import pandas as pd
import numpy as np

def answer_one():

    # Read file and skip useless rows
    energy = pd.ExcelFile('Energy Indicators.xls')
    energy = pd.read_excel(energy, 0, skiprows=17, skipfooter=38)

    # Catch columns of interest and rename them
    energy = energy[['Unnamed: 1', 'Petajoules', 'Gigajoules', '%']]
    energy = energy.rename(columns={'Unnamed: 1': 'Country',
                                'Petajoules': 'Energy Supply',
                                'Gigajoules': 'Energy Supply per Capita',
                                '%': '% Renewable'})

    # Treating missing values and converting energy in petajoules to gigajoules
    energy['Energy Supply'].replace('...', np.nan, inplace=True)
    energy['Energy Supply'] = energy['Energy Supply'] * 1000000

    # Renaming some values and cleaning the country's name's format
    energy['Country'].replace({'Republic of Korea':'South Korea',
                            'United States of America':'United States',
                            'United Kingdom of Great Britain and Northern Ireland':'United Kingdom',
                            'China, Hong Kong Special Administrative Region':'Hong Kong'}, inplace=True)
    energy['Country'].replace(r' \(.*\)', '',regex=True, inplace=True)
    energy['Country'].replace(r' \d', '',regex=True, inplace=True)

    # Reading file and skiping useless rows
    gdp = pd.read_csv('world_bank.csv', skiprows=4)

    # Replacing values
    gdp['Country Name'].replace({"Korea, Rep.": "South Korea",  "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"}, inplace=True)

    # Slicing columns of interest
    gdp = gdp[['Country Name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
    gdp.rename(columns={'Country Name': 'Country'}, inplace=True)

    # Reading file and keeping only the top 15
    ScimEn = pd.read_excel('scimagojr-3.xlsx')
    ScimEn = ScimEn[:15]

    # Joining all three DataFrame
    sci_energy = pd.merge(ScimEn, energy, how='inner', left_on='Country', right_on='Country')
    merged = pd.merge(sci_energy, gdp, how='inner', left_on='Country', right_on='Country')
    merged = merged.set_index('Country')
    return merged

    raise NotImplementedError()

In [95]:
def answer_two():

    # First, we need to know the length of all DataFrame objects combined,
    # then, we subtract from the final merged DataFrame

    # Reading all DataFrames and then concatenating them
    # This is just the same first steps of answer_one function

    # Read file and skip useless rows
    energy = pd.ExcelFile('assets/Energy Indicators.xls')
    energy = pd.read_excel(energy, 0, skiprows=17, skipfooter=38)

    # Catch columns of interest and rename them
    energy = energy[['Unnamed: 1', 'Petajoules', 'Gigajoules', '%']]
    energy = energy.rename(columns={'Unnamed: 1': 'Country',
                                'Petajoules': 'Energy Supply',
                                'Gigajoules': 'Energy Supply per Capita',
                                '%': '% Renewable'})

    # Treating missing values and converting energy in petajoules to gigajoules
    energy['Energy Supply'].replace('...', np.nan, inplace=True)
    energy['Energy Supply'] = energy['Energy Supply'] * 1000000

    # Renaming some values and cleaning the country's name's format
    energy['Country'].replace({'Republic of Korea':'South Korea',
                            'United States of America':'United States',
                            'United Kingdom of Great Britain and Northern Ireland':'United Kingdom',
                            'China, Hong Kong Special Administrative Region':'Hong Kong'}, inplace=True)
    energy['Country'].replace(r' \(.*\)', '',regex=True, inplace=True)
    energy['Country'].replace(r' \d', '',regex=True, inplace=True)

    # Reading file and skiping useless rows
    gdp = pd.read_csv('assets/world_bank.csv', skiprows=4)

    # Replacing values
    gdp['Country Name'].replace({"Korea, Rep.": "South Korea",  "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"}, inplace=True)

    # Slicing columns of interest
    gdp = gdp[['Country Name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
    gdp.rename(columns={'Country Name': 'Country'}, inplace=True)

    # Reading file and keeping all rows
    ScimEn = pd.read_excel('assets/scimagojr-3.xlsx')

    # Putting everything together
    merged = pd.merge(ScimEn, energy, how='inner',left_on='Country', right_on='Country')
    merged = pd.merge(merged, gdp, how='inner', left_on='Country', right_on='Country')
    merged = merged.set_index('Country')

    concatenated = pd.concat([ScimEn, gdp, energy])['Country'].unique()

    return len(concatenated) - len(merged)
    raise NotImplementedError()

In [96]:
def answer_three():

    # Keeping only the columns of interest
    top_fifteen = answer_one()
    top_fifteen = top_fifteen[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]

    # Applying mean function and then sorting data
    avg = top_fifteen.apply(np.nanmean, axis=1)
    avg = avg.sort_values(ascending=False)

    return avg
    raise NotImplementedError()

In [97]:
top_15 = answer_three()
data = answer_one()

top_15

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
dtype: float64

In [98]:
country = top_15[top_15 == top_15[5]].index[0]

diff = data.loc[country]['2015'] - data.loc[country]['2006']

diff

246702696075.3999

In [99]:
def answer_four():
    # First we need to get the 6th largest average GDP
    # And get the data from 2006 to 2015

    top_15 = answer_three()
    data = answer_one()

    # Then we figure out what country it is
    country = top_15[top_15 == top_15[5]].index[0]

    # And calculate the difference
    diff = data.loc[country]['2015'] - data.loc[country]['2006']

    return diff
    raise NotImplementedError()

In [100]:
top_fifteen = answer_one()
top_fifteen = top_fifteen['Energy Supply per Capita']
avg_energy = top_fifteen.mean()
avg_energy

157.6

In [101]:
top_fifteen = answer_one()
top_percentage = top_fifteen['% Renewable'].max()
top_percentage

69.64803

In [113]:
country = top_fifteen.where(top_fifteen['% Renewable'] == top_percentage).dropna()
country.iloc[0].name

'Brazil'

In [24]:
top_fifteen['% Renewable'] == top_percentage

Rank
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
Name: % Renewable, dtype: bool

In [25]:
def answer_five():
    top_fifteen = answer_one()
    top_fifteen = top_fifteen['Energy Supply per Capita']
    avg_energy = top_fifteen.mean()
    return avg_energy

    raise NotImplementedError()

In [117]:
def answer_six():

    # First we get the maximum value of the desired column
    top_fifteen = answer_one()
    top_percentage = top_fifteen['% Renewable'].max()

    # Then we discover what country it is
    country = top_fifteen.where(top_fifteen['% Renewable'] == top_percentage).dropna()
    country = country.iloc[0].name

    return (country, top_percentage)
    raise NotImplementedError()

In [115]:
top_15 = answer_one()
top_15['Ratio'] = top_15['Self-citations']/top_15['Citations']
max_val = top_15['Ratio'].max()
country = top_15.where(top_15['Ratio'] == max_val).dropna()
country = country.iloc[0].name
max_val, country

(0.6893126179389422, 'China')

In [116]:
def answer_seven():

    # Creating the new column
    top_15 = answer_one()
    top_15['Ratio'] = top_15['Self-citations']/top_15['Citations']

    # Finding max value and its country
    max_val = top_15['Ratio'].max()
    country = top_15.where(top_15['Ratio'] == max_val).dropna()
    country = country.iloc[0].name

    return (country, max_val)
    raise NotImplementedError()

In [119]:
top_15 = answer_one()
top_15['Population Estimate'] = top_15['Energy Supply']/top_15['Energy Supply per Capita']
p_e = top_15['Population Estimate'].sort_values(ascending=False)
third = top_15.where(top_15['Population Estimate'] == p_e[2]).dropna()
third = third.iloc[0].name
third

'United States'

In [30]:
def answer_eight():

    # Creating new column
    top_15 = answer_one()
    top_15['Population Estimate'] = top_15['Energy Supply']/top_15['Energy Supply per Capita']

    # Obtaining the third most populous country's name
    p_e = top_15['Population Estimate'].sort_values(ascending=False)
    third = top_15.where(top_15['Population Estimate'] == p_e[2]).dropna()
    third = third.iloc[0].name
    return third
    raise NotImplementedError()

In [31]:
top15 = answer_one()
top15['Population Estimate'] = top15['Energy Supply']/top15['Energy Supply per Capita']
top15['Citable Documents per Capita'] = top15['Citable documents']/top15['Population Estimate']

top15['Citable Documents per Capita'] = top15['Citable Documents per Capita'].astype(float)
top15['Energy Supply per Capita'] = top15['Energy Supply per Capita'].astype(float)

# Pearson's Correlation
pearson = top15['Citable Documents per Capita'].corr(top15['Energy Supply per Capita'])
pearson

0.7940010435442946

In [32]:
def answer_nine():

    # Create columns
    top15 = answer_one()
    top15['Population Estimate'] = top15['Energy Supply']/top15['Energy Supply per Capita']
    top15['Citable Documents per Capita'] = top15['Citable documents']/top15['Population Estimate']

    # Convert to float
    top15['Citable Documents per Capita'] = top15['Citable Documents per Capita'].astype(float)
    top15['Energy Supply per Capita'] = top15['Energy Supply per Capita'].astype(float)

    # Pearson's Correlation
    pearson = top15['Citable Documents per Capita'].corr(top15['Energy Supply per Capita'])
    return pearson
    raise NotImplementedError()

In [33]:
top_15 = answer_one()
top_15['HighRenew'] = [1 if x >= top_15['% Renewable'].median() else 0 for x in top_15['% Renewable']]
top_15['HighRenew']

Rank
1     1
2     0
3     0
4     0
5     1
6     1
7     1
8     0
9     1
10    0
11    1
12    1
13    0
14    0
15    1
Name: HighRenew, dtype: int64

In [34]:
def answer_ten():

    # Creating new column and filling it with List Comprehension
    top_15 = answer_one()
    top_15['HighRenew'] = [1 if x >= top_15['% Renewable'].median() else 0 for x in top_15['% Renewable']]

    return top_15['HighRenew']
    raise NotImplementedError()

In [40]:
ContinentDict  = {'China':'Asia',
              'United States':'North America',
              'Japan':'Asia',
              'United Kingdom':'Europe',
              'Russian Federation':'Europe',
              'Canada':'North America',
              'Germany':'Europe',
              'India':'Asia',
              'France':'Europe',
              'South Korea':'Asia',
              'Italy':'Europe',
              'Spain':'Europe',
              'Iran':'Asia',
              'Australia':'Australia',
              'Brazil':'South America'}

top15 = answer_one()
top15 = top15.reset_index()
top15['Population Estimate'] = top15['Energy Supply']/top15['Energy Supply per Capita']
top15['Continent'] = [ContinentDict[country] for country in top15['Country']]
top15['Continent']

0              Asia
1     North America
2              Asia
3            Europe
4            Europe
5     North America
6            Europe
7              Asia
8            Europe
9              Asia
10           Europe
11           Europe
12             Asia
13        Australia
14    South America
Name: Continent, dtype: object

In [63]:
continents = top15[['Continent', 'Population Estimate']]
continents = continents.groupby('Continent')
continents

In [64]:
continents = continents.aggregate(size=pd.NamedAgg(column='Population Estimate', aggfunc=np.size),
                                  sum=pd.NamedAgg(column='Population Estimate', aggfunc=np.sum),
                                  mean=pd.NamedAgg(column='Population Estimate', aggfunc=np.mean),
                                  std=pd.NamedAgg(column='Population Estimate', aggfunc=np.nanstd))
continents

               size               sum          mean           std
Continent
Asia              5   2898666386.6106  5.797333e+08  6.790979e+08
Australia         1   23316017.316017  2.331602e+07           NaN
Europe            6  457929667.216372  7.632161e+07  3.464767e+07
North America     2   352855249.48025  1.764276e+08  1.996696e+08
South America     1  205915254.237288  2.059153e+08           NaN

In [129]:
def answer_eleven():

    # Dict
    ContinentDict  = {'China':'Asia',
                  'United States':'North America',
                  'Japan':'Asia',
                  'United Kingdom':'Europe',
                  'Russian Federation':'Europe',
                  'Canada':'North America',
                  'Germany':'Europe',
                  'India':'Asia',
                  'France':'Europe',
                  'South Korea':'Asia',
                  'Italy':'Europe',
                  'Spain':'Europe',
                  'Iran':'Asia',
                  'Australia':'Australia',
                  'Brazil':'South America'}

    # Attaining top 15 and calculating population estimate
    top15 = answer_one()
    top15['Population Estimate'] = top15['Energy Supply']/top15['Energy Supply per Capita']
    top15['Continent'] = [ContinentDict[country] for country in top15.index]

    # Creating GroupBy object
    continents = top15[['Continent', 'Population Estimate']]
    continents = continents.groupby('Continent')

    # Aggregating data
    continents = continents.aggregate(size=pd.NamedAgg(column='Population Estimate', aggfunc=np.size),
                                  sum=pd.NamedAgg(column='Population Estimate', aggfunc=np.sum),
                                  mean=pd.NamedAgg(column='Population Estimate', aggfunc=np.mean),
                                  std=pd.NamedAgg(column='Population Estimate', aggfunc=np.nanstd))

    return continents
    raise NotImplementedError()

answer_eleven()

               size               sum          mean           std
Continent
Asia              5   2898666386.6106  5.797333e+08  6.790979e+08
Australia         1   23316017.316017  2.331602e+07           NaN
Europe            6  457929667.216372  7.632161e+07  3.464767e+07
North America     2   352855249.48025  1.764276e+08  1.996696e+08
South America     1  205915254.237288  2.059153e+08           NaN

In [36]:
top15 = answer_one()
ContinentDict  = {'China':'Asia',
              'United States':'North America',
              'Japan':'Asia',
              'United Kingdom':'Europe',
              'Russian Federation':'Europe',
              'Canada':'North America',
              'Germany':'Europe',
              'India':'Asia',
              'France':'Europe',
              'South Korea':'Asia',
              'Italy':'Europe',
              'Spain':'Europe',
              'Iran':'Asia',
              'Australia':'Australia',
              'Brazil':'South America'}
top15 = top15.reset_index()
top15['Continent'] = [ContinentDict[country] for country in top15['Country']]
top15['% Renewable'] = pd.cut(top15['% Renewable'],5)
top15=top15.groupby(['Continent','% Renewable']).size()
top15[top15>0]

Continent      % Renewable
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
dtype: int64

In [124]:
def answer_twelve():

    # Top 15 and Dict
    top15 = answer_one()
    ContinentDict  = {'China':'Asia',
                  'United States':'North America',
                  'Japan':'Asia',
                  'United Kingdom':'Europe',
                  'Russian Federation':'Europe',
                  'Canada':'North America',
                  'Germany':'Europe',
                  'India':'Asia',
                  'France':'Europe',
                  'South Korea':'Asia',
                  'Italy':'Europe',
                  'Spain':'Europe',
                  'Iran':'Asia',
                  'Australia':'Australia',
                  'Brazil':'South America'}

    # Reseting index and creating column
    top15 = top15.reset_index()
    top15['Continent'] = [ContinentDict[country] for country in top15['Country']]

    # Cutting column into 5 bins and attaining their sizes
    top15['% Renewable'] = pd.cut(top15['% Renewable'],5)
    top15=top15.groupby(['Continent','% Renewable']).size()

    return top15  # It seems that when the zero values are dropped, the answer is incorrect
    raise NotImplementedError()


answer_twelve()

Continent      % Renewable
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Australia      (2.212, 15.753]     1
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
               (42.701, 56.174]    0
               (56.174, 69.648]    0
North America  (2.212, 15.753]     1
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    1
South America  (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    1
dtype: int64

In [131]:
top15 = answer_one()
top15['Population Estimate'] = top15['Energy Supply']/top15['Energy Supply per Capita']
top15['Population Estimate'].apply(lambda x: '{0:,}'.format(x)).astype(str)

Country
China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                    77,075,630.25210084
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: Population Estimate, dtype: object

In [132]:
def answer_thirteen():
    top15 = answer_one()
    top15['Population Estimate'] = top15['Energy Supply']/top15['Energy Supply per Capita']
    return top15['Population Estimate'].apply(lambda x: '{0:,}'.format(x)).astype(str)
    raise NotImplementedError()

Nothing can describe what I'm feeling right now than this: https://www.youtube.com/watch?v=gKQOXYB2cd8&ab_channel=groundbeefmosque. Honestly, I'm exhausted.