<a href="https://colab.research.google.com/github/brunofbpaula/DataScience-UM-Coursera/blob/main/Pandas/DataFrame/Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexing

The index is essentially a row level label, and in pandas the rows correspond to axis 0. Indices can be either autogenerated or set explicitly. Another option for setting an index is to use the set_index() function, that takes a list of columns and promotes those columns to index.

In [9]:
import pandas as pd

# Create DataFrame
admissions_df = pd.read_csv('dataset/Admission_Predict.csv', index_col=0)

# Clean up columns names
cols = admissions_df.columns
cols = [x.strip() for x in cols]
admissions_df.columns = cols

admissions_df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [10]:
# Changing the DataFrame index from Serial No. to Chance of Admit

# Saving the indexed data to its own (new) column
admissions_df['Serial Number'] = admissions_df.index

# Setting the index to another column
admissions_df = admissions_df.set_index('Chance of Admit')

admissions_df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Serial Number
Chance of Admit,,,,,,,,
0.92,337,118,4,4.5,4.5,9.65,1,1
0.76,324,107,4,4.0,4.5,8.87,1,2
0.72,316,104,3,3.0,3.5,8.00,1,3
0.80,322,110,3,3.5,2.5,8.67,1,4
0.65,314,103,2,2.0,3.0,8.21,0,5

If we want to reset the index, we can do so by using the reset function. It will make the current index a new column and create a default numbered index.

In [11]:
admissions_df = admissions_df.reset_index()
admissions_df.head()

,Chance of Admit,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Serial Number
0,0.92,337,118,4,4.5,4.5,9.65,1,1
1,0.76,324,107,4,4.0,4.5,8.87,1,2
2,0.72,316,104,3,3.0,3.5,8.00,1,3
3,0.80,322,110,3,3.5,2.5,8.67,1,4
4,0.65,314,103,2,2.0,3.0,8.21,0,5

## Census dataset

In this dataset there are two summarized levels, one that contains summary data for whole county, and one that contains summary data for each state.

In [13]:
census = pd.read_csv('dataset/census.csv')

census.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [15]:
# We see that the possible values for the sum level are using the unique function
# on the DataFrame, which is similar to the SQL distinct operator

# Running unique on the sum level
census['SUMLEV'].unique()

array([40, 50])

In [17]:
# There are only two values. Let's exclude all of the rows that are summaries
# at the state level and just keep the country data.
census = census[census['SUMLEV'] == 50]
census.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [19]:
# Reducing the data to just the total population estimates and number of births
target_columns = ['STNAME', 'CTYNAME', 'BIRTHS2010', 'BIRTHS2011', 'BIRTHS2012', 'BIRTHS2013', 'BIRTHS2014', 'BIRTHS2015',
                'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015']

census = census[target_columns]
census.head()

,STNAME,CTYNAME,BIRTHS2010,BIRTHS2011,BIRTHS2012,BIRTHS2013,BIRTHS2014,BIRTHS2015,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,Alabama,Autauga County,151,636,615,574,623,600,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,517,2187,2092,2160,2186,2240,186659,190396,195126,199713,203709
3,Alabama,Barbour County,70,335,300,283,260,269,27226,27159,26973,26815,26489
4,Alabama,Bibb County,44,266,245,259,247,253,22733,22642,22512,22549,22583
5,Alabama,Blount County,183,744,710,646,618,603,57711,57776,57734,57658,57673

In [20]:
# Setting the a multi-column index
census = census.set_index(['STNAME', 'CTYNAME'])
census.head()

                        BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME  CTYNAME
Alabama Autauga County         151         636         615         574
        Baldwin County         517        2187        2092        2160
        Barbour County          70         335         300         283
        Bibb County             44         266         245         259
        Blount County          183         744         710         646

                        BIRTHS2014  BIRTHS2015  POPESTIMATE2011  \
STNAME  CTYNAME
Alabama Autauga County         623         600            55253
        Baldwin County        2186        2240           186659
        Barbour County         260         269            27226
        Bibb County            247         253            22733
        Blount County          618         603            57711

                        POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  \
STNAME  CTYNAME
Alabama Autauga County            55175            55038            55290
        Baldwin County           190396           195126           199713
        Barbour County            27159            26973            26815
        Bibb County               22642            22512            22549
        Blount County             57776            57734            57658

                        POPESTIMATE2015
STNAME  CTYNAME
Alabama Autauga County            55347
        Baldwin County           203709
        Barbour County            26489
        Bibb County               22583
        Blount County             57673

In [22]:
# Getting data for a specific county in a specific state
census.loc['Michigan', 'Alcona County']

BIRTHS2010            20
BIRTHS2011            61
BIRTHS2012            59
BIRTHS2013            66
BIRTHS2014            64
BIRTHS2015            58
POPESTIMATE2011    10775
POPESTIMATE2012    10607
POPESTIMATE2013    10572
POPESTIMATE2014    10448
POPESTIMATE2015    10349
Name: (Michigan, Alcona County), dtype: int64

In [23]:
# Comparing two different counties from different states
# We need to pass the indexes in a tuple
census.loc[ [('Michigan', 'Alcona County'),
             ('Michigan', 'Marquette County')] ]

                           BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME   CTYNAME
Michigan Alcona County             20          61          59          66
         Marquette County         157         637         691         649

                           BIRTHS2014  BIRTHS2015  POPESTIMATE2011  \
STNAME   CTYNAME
Michigan Alcona County             64          58            10775
         Marquette County         584         602            67452

                           POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  \
STNAME   CTYNAME
Michigan Alcona County               10607            10572            10448
         Marquette County            67813            67757            67675

                           POPESTIMATE2015
STNAME   CTYNAME
Michigan Alcona County               10349
         Marquette County            67215